# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - master
      - 1.*

  pull_request:
    branches:
      - master
      - 1.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Tests with Maven
        run: ./mvnw clean install
      - name: Check Code Style
        run: ./mvnw clean install checkstyle:check -DskipTests
      - name: Check FindBugs
        run: ./mvnw clean install findbugs:check -DskipTests
      - name: Build with Maven
        run: ./mvnw clean install package
